### ISSUE TITLE
Issues with python create_primers.py

### ISSUE THREAD

**Issue by temmorrison** [jbloomlab/CodonTilingPrimers#2]
My laboratory is based at the University of Colorado and investigates various aspects of arbovirus infection and immunity. Based in part on some of your work, we are developing a chikungunya virus deep mutational scanning project, and we have encountered some issues generating the primer sequences for codon mutagenesis. I’m hoping you might be able to help us. I have outlined the issues below. We are not sure why these errors occur. We are running Python 3.7.3 and we are not aware of issues with the system, but honestly, we are not highly experienced with the use of Python scripts-still learning. Any insight would be greatly appreciated!

Best, Tem

We went to your GitHub site, downloaded the folder, and unzipped the files (see below):

test@breck-super1:/Tools$ unzip CodonTilingPrimers-master.zip 
Archive:  CodonTilingPrimers-master.zip
24dd33651d409cfd414ccf0da4113072ef39edf6
   creating: CodonTilingPrimers-master/
 extracting: CodonTilingPrimers-master/.gitignore  
  inflating: CodonTilingPrimers-master/EN72-HA.txt  
  inflating: CodonTilingPrimers-master/EN72-HA_primers.txt  
  inflating: CodonTilingPrimers-master/HughSchematic.pdf  
  inflating: CodonTilingPrimers-master/JesseLabNotes.pdf  
  inflating: CodonTilingPrimers-master/LICENSE  
  inflating: CodonTilingPrimers-master/README.rst  
  inflating: CodonTilingPrimers-master/create_primers.py  

We attempted to access the help file:

test@breck-super1:/Tools/CodonTilingPrimers-master$ python create_primers.py -h
  File "create_primers.py", line 234
    print "Read a sequence of length %d from %s:\n%s" % (len(sequence), sequencefile, sequence)
                                                    ^
SyntaxError: invalid syntax

We also tried to run the example:

test@breck-super1:/Tools/CodonTilingPrimers-master$ python create_primers.py EN72-HA.txt EN72 1 En72-HA_primers.txt 
  File "create_primers.py", line 234
    print "Read a sequence of length %d from %s:\n%s" % (len(sequence), sequencefile, sequence)
                                                    ^
SyntaxError: invalid syntax

**Comment by jbloom** [comment]
@ajgreaney @tylernstarr: Can you push branches and create pull requests for any changes you've made to the scripts that make them work on `python3` (and also possibly that implement `NNS`), and then we can merge them to fix this issue hopefully mostly off the existing code that you're using?

**Comment by jbloom** [comment]
@temmorrison:

Your problems show now be fixed in the current version in GitHub (commit 95beb5398e). The script now works with `python3`.

Note that there is also now an option to design `NNS` or `NNK` primers rather than `NNN` ones (i.e., `--ambiguous_codon NNS`). This option may be preferable to `NNN` for some purposes, and we have started doing it in some of our experiments. See [here](https://en.wikipedia.org/wiki/Saturation_mutagenesis) for rationale if you are not familiar with this.
